// AUTH
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const CLEAR_AUTH_ERROR = "CLEAR_AUTH_ERROR";

// USER PROFILE AND DASHBOARD
export const LOAD_PROFILE = "LOAD_PROFILE";
export const SET_PROFILE = "SET_PROFILE";
export const LOAD_PROFILE_FAILED = "LOAD_PROFILE_FAILED";
export const JOIN_CLASSROOM_STUDENT = "JOIN_CLASSROOM_STUDENT";
export const JOIN_CLASSROOM_TEACHER = "JOIN_CLASSROOM_TEACHER";
export const CREATE_CLASSROOM = "CREATE_CLASSROOM";
export const PROFILE_OPERATION_LOAD_START = "PROFILE_OPERATION_LOAD_START";
export const PROFILE_OPERATION_LOAD_STOP = "PROFILE_OPERATION_LOAD_STOP";
export const PROFILE_OPERATION_ERROR = "PROFILE_OPERATION_ERROR";
export const CLEAR_PROFILE_OPERATION_ERROR = "CLEAR_PROFILE_OPERATION_ERROR";
export const UPDATE_PROFILE_PICTURE = "UPDATE_PROFILE_PICTURE";
export const UPDATE_PROFILE_PASSWORD = "UPDATE_PROFILE_PASS";
export const LEAVE_CLASSROOM = "LEAVE_CLASSROOM";
export const CLOSE_ACCOUNT = "CLOSE_ACCOUNT";

// CLASSROOM
export const LOAD_CLASSROOM = "LOAD_CLASSROOM";
export const SET_CLASSROOM = "SET_CLASSROOM";
export const LOAD_CLASSROOM_FAILED = "LOAD_CLASSROOM_FAILED";
export const ADD_LECTURE = "ADD_LECTURE";
export const SET_CURRENT_LECTURE = "CURRENT_LECTURE";
export const ADD_NOTE = "ADD_NOTE";
export const ADD_ANNOUNCEMENT = "ADD_ANNOUNCEMENT";
export const CLASSROOM_OPERTAION_LOAD_START = "CLASSROOM_OPERTAION_LOAD_START";
export const CLASSROOM_OPERTAION_LOAD_STOP = "CLASSROOM_OPERTAION_LOAD_STOP";
export const CLASSROOM_OP_ERROR = "CLASSROOM_ERROR_OP";
export const CLEAR_CLASSROOM_OP_ERROR = "CLEAR_CLASSROOM_OPERATION_ERROR";
export const DELETE_LECTURE_NOTE = "DELETE_LECTURE_NOTE";
export const DELETE_ANNOUNCEMENT = "DELETE_ANNOUNCEMENT";
export const UPGRADE_TO_HEAD = "UPGRADE_TO_HEAD";
export const DELETE_LECTURE = "DELETE_LECTURE";
export const REMOVE_STUDENT = "REMOVE_STUDENT";
export const REMOVE_TEACHER = "REMOVE_TEACHER";
export const DELETE_CLASSROOM = "DELETE_CLASSROOM";
export const CLEAR_CLASSROOM = "CLEAR_CLASSROOM";
export const CLEAR_REDIRECTS = "CLEAR_REDIRECTS";

// INFO
export const INFO_MSG = "INFO_MSG";
export const ERROR_MSG = "ERROR_MSG";
export const CLEAR_INFO_MSG = "CLEAR_INFO_MSG";
export const CLEAR_ERROR_MSG = "CLEAR_ERROR_MSG";
